name: Centralized workflow
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ui:
    # Use the shared workflow from https://github.com/folio-org/.github
    uses: folio-org/.github/.github/workflows/ui.yml@v1
    # Only handle push events from the main branch or tags, to decrease PR noise
    # if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push' || github.ref_type == 'tag'
    with:
      sonar-sources: ./lib
      generate-module-descriptor: false # Shared libraries do not need module descriptors, they're an okapi thing
      publish-module-descriptor: false
    secrets: inherit
